// Common dog-related API helpers and constants

export const DOG_ALLOWED_COLUMNS = [
  "user_id",
  "name",
  "gender",
  "breed",
  "age_years",
  "size",
  "weight_kg",
  "pedigree_certified",
  "dna_tested",
  "vaccinated",
  "hip_elbow_tested",
  "heart_tested",
  "eye_tested",
  "genetic_panel",
  "thyroid_tested",
  "coat_type",
  "color",
  "activity_level",
  "sociability",
  "trainability",
];

export const DOG_LIST_COLUMNS = [
  "id",
  "name",
  "breed",
  "gender",
  "age_years",
  "weight_kg",
  "size",
  "color",
  "image_url",
  "user_id",
  "created_at",
  "match_requests_count",
  "match_accept_count",
  "match_completed_count",
  "match_success_count",
  "match_failure_count",
  "female_successful_matings",
  "male_success_rate",
];
